dist: focal
os: linux
language: node_js
node_js:
  - 15

install:
  - npm install

script:
  - $(npm bin)/csval inventory.csv rules.json
  - ./trigger-build.sh $TRAVIS_TOKEN

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  strategy: git
  edge: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: main
