dist: focal
os: linux

before_install:
  - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
  - sudo apt-get install -y nodejs > /dev/null

install:
  - npm install

script:
  - $(npm bin)/csval inventory.csv rules.json

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  strategy: git
  edge: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: main
